export type Song = {
  slug: string
  title: string
  category: string
  lines: string[]
}

export const allSongs: Song[] = [
  {
    slug: 'sueni-mebi-dhong',
    title: 'Sueni Mebi Dhong',
    category: 'original',
    lines: [
      'Tayi Tayi Sueni Mebei Dhong Gi',
      'Gawai Gazum Toen Dhi Dhoep Mae',
      'Rangwa Mebei Nge Gi Sem Gi',
      'Choe Bay Sa Phu Dhi Jow Mae',
      '',
      'Nge Sem Gi Lab Dho Zum Bay Bewa Chin',
      'Choe Lu Gawai Tam Tshu Shay Dhi Lab Dha Lo',
      'Dunghay Gi Lab Dho Zum Bay Bewa Chin',
      'Choe Phama Tab Dhi Tang Ra Matang Lo',
      '',
      'Namkhai Karma Mindu Choe',
      'Nge Minpa Selwai Thridu Nyima',
      'Nge Jamtshoi Norbu Choe',
      'Dhue Tabu Nga Da Chha Dhi Dhoe Na',
      '',
      'Joyi Joyi Loni Mebi Sem Gi',
      'Choe Gi Dhunghay Ting Da Dhoeb Mae',
      'Wangtshay Mebi Nge Gi Sem Dhi',
      'Choe Gi Len Ni Yoeb Chi Bay Nang',
      '',
      'Nge Sem Gi Lab Dho Zum Bay Bewa Chin',
      'Choe Lu Gawai Tam Tshu Shay Dhi Lab Dha Lo',
      'Dunghay Gi Lab Dho Zum Bay Bewa Chin',
      'Choe Phama Tab Dhi Tang Ra Matang Lo',
      '',
      'Nge Driwi Len En Choe',
      'Nge Sem Lu Dokpa Me',
      'Nga So Da Drel So Ru',
      'Choe Korlay Cheri Zhawong',
      '',
      'Namkhai Karma Mindu Choe',
      'Nge Minpa Selwai Thridu Nyima',
      'Nge Jamtshoi Norbu Choe',
      'Dhue Tabu Nga Da Chha Dhi Dhoe Na',
    ],
  },
  {
    slug: 'zhawong-ga',
    title: 'Zhawong Ga',
    category: 'original',
    lines: [
      'Choe Dha Nga Chhu Da Nyamo',
      'Zumbay Dhoeni Yoeru Ra',
      'Choe Dha Nga Zu Dha Geema',
      'Zumbay Dhoeni Yoeru Ra',
      '',
      'Gani Mae Lo Ja Da Tong Bay',
      'Choe Dha Dhoeni Yoeba Chin',
      'Gani Mae Nge Mitshay Chip Dhi',
      'Choe Dha Zoni Yoeba Chin',
      '',
      'Mitshay Takpa Tenpa Me',
      'Dha Dhuetshay Rendho Zum',
      'Dhuetshay Rang Lu Guni Me',
      'Da Bung Ya Chhay Dho Zum',
      '',
      'Gadem Chi Bay Zamling Na Nga Mingo Zerwa Chin',
      'Enru Choe Gi Nga Lendhi Ra Zhawong Ga',
      'Gadem Chi Bay Zamling Na Nga Mingo Zerwa Chin',
      'Enru Choe Gi Nga Lendhi Ra Zhawong Ga',
      '',
      'Nge Tshay Chip Dhi Na',
      'Choe Dha Dhoeni Yoen',
      'Zamling Na Nga Mazha Ru',
      'Choe Gi Zhawi Rewa Yoe',
      '',
      'Gadem Chi Bay Zamling Na Nga Mingo Zerwa Chin',
      'Enru Choe Gi Nga Lendhi Ra Zhawong Ga',
      'Gadem Chi Bay Zamling Na Nga Mingo Zerwa Chin',
      'Enru Choe Gi Nga Lendhi Ra Zhawong Ga',
    ],
  },
  {
    slug: 'chhemla',
    title: 'Chhemla',
    category: 'original',
    lines: [
      'Pangsho Nang Gi Chhemla Nga Phudhi',
      'Ro Laebi Meto Dhumra Nang Hoedho',
      'Nge Gasho Pangoen Meto Shar Nu',
      'Nga Dhi Gu Chha Dhi Drangtse Thum Da Lu',
      '',
      'Dhue Nam Ya Matsho Wai Dro Nge Kha Gu Reb Dha Lu',
      'Nga Pangsho Nang Gi Chhemla Choe Dhoesa Chha Go Nouyi',
      'Nga Pangsho Nang Gi Chhemla Choe Dhoesa Chha Go Nouyi',
      '',
      'Pangsho Nang Gi Chhemla Nga Phudhi',
      'Ro Laebi Meto Dhumra Nang Hoedho',
      'Nge Gasho Pangoen Meto Shar Nu',
      'Nga Dhi Gu Chha Dhi Drangtse Thum Dha Lu',
      '',
      'Ro Laebi Meto Dhumra Nang',
      'Nge Gasho Pangoen Meto Gu',
      'Ro Zhen Me Chhemla Chha Dhi Dhu',
      'Nga Dhi Gu Chabi Rangwa Me',
      '',
      'Pangsho Nang Gi Chhemla Nga Phudhi',
      'Nam Tong Be Nang Lu Phudhi Jodho',
      'Nge Gasho Pangoen Meto Thong Ru',
      'Nga Dhi Gu Chha Be Rangwa Nga Lu Me',
    ],
  },
  {
    slug: 'dren-ni-yoega',
    title: 'Dren Ni Yoega',
    category: 'original',
    lines: [
      'Phudhi Yasi Namkhai Bulay',
      'Bja Karp Gi Nang Na Lu',
      'Phakha Hoechi Jamtshoi Phakha',
      'Bu Nge Gi Yewongma',
      '',
      'Choe Nga Dren Ni Yoe Ga',
      'Nga Choe Dren Dhi Ra Yoe',
      'Nam Guen Gi Khaw Chab Da Lu',
      'Choe Nge Phama Hoewong Ga',
      '',
      'Nosam Tang Rey Tang Tshay',
      'Choe Gi Nosam Mae',
      'Nyilam Thong Ray Thong Tshay',
      'Choe Gi Nyilam Mae',
      '',
      'Hemai Dhuetshay Tshu Paar Na Tadhi Lue',
      'Go Dangpa Chay Be Sago Na Gudhi Yoe',
      '',
      'Choe Nga Dren Ni Yoe Ga',
      'Nga Choe Dren Dhi Ra Yoe',
      'Nam Guen Gi Khaw Chab Da Lu',
      'Choe Nge Phama Hoewong Ga',
      '',
      'Nosam Tang Rey Tang Tshay',
      'Choe Gi Nosam Mae',
      'Nyilam Thong Ray Thong Tshay',
      'Choe Gi Nyilam Mae',
    ],
  },
]
